# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V${project.version} BETA Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config file for commands and messages, place holders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# ------------------------------------------
# Don't change the config version!

Config Version: 4

# Checks if an update is available and notifies staff, uses Spigot
Update Checks: true

Metrics: true

Crates:
  Example:
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Name: '&6&lSword of Destiny'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-3
      '2':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Name: NONE
        Item Data: 0
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2
      '3':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Commands:
        - 'spawner give %name% spider'
        - 'say %name% opened a crate'
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2

# Modify different options of the crate key
Crate Keys:
  Item: TRIPWIRE_HOOK
  Name: "%type% Crate Key"
  Enchanted: true

# If true it will stop players without the admin perm breaking crates
Crate Protection: false

# Up to 4 lines for the hologram, %crate% can be used to show the crate name
Hologram Text:
- "%crate%"
- "Right-Click to Open!"
- "Left-Click to Preview!"

# Enable the BETA animation's for CratesPlus
Enable GUI Beta Animation: false


# Below are all messages that can be edited in the plugin
Messages:
  Prefix: "&7[&bCratesPlus&7]"
  Command No Permission: "&cYou do not have the correct permission to run this command"
  Crate Open Without Key: "&cYou must be holding a %crate% &ckey to open this crate"
  Key Given: "&aYou have been given a %crate% &acrate key"
  Broadcast: "&d%displayname% &dopened a %crate% &dcrate"
  Cant Place: "&cYou can not place crate keys"