# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V${project.version} Config
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config and messages file, placeholders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# - %prize% - The name of the winning.
# - %percentage% - Percentage of the winning, useful for "Chance Message".
# ------------------------------------------
# Don't change the config version!

Config Version: 6

# Checks if an update is available and notifies staff
Update Checks: true
Update Branch: "spigot"

# Uploads anonymous data about your server, used for general statics
Metrics: true

Crates:
  Example:
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
    Block: GLASS
    Preview: true
    Hide Percentages: true
    Permission: cratesplus.crate.example # Permissions can be anything, it will check that the player has the permission before opening
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Winnings:
      '1':
        Type: ITEM
        Item Type: IRON_SWORD
        Item Data: 0
        Percentage: 50
        Name: '&6&lSword of Destiny'
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-3
        Lore:
        - "Testing123"
      '2':
        Type: ITEM
        Item Type: DIAMOND_SWORD
        Name: NONE
        Item Data: 0
        Percentage: 25
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2
      '3':
        Type: COMMAND
        Item Type: MOB_SPAWNER
        Percentage: 25
        Commands:
        - 'spawner give %name% spider'
        - 'say %name% opened a crate'
        Name: '&e&lSpider Spawner'
        Item Data: 0
        Amount: 1
        Enchantments:
        - DAMAGE_ALL-5
        - DURABILITY-3
        - FIRE_ASPECT-2
  AnotherExample:
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN
    Block: GLASS
    Preview: true
    Permission: cratesplus.crate.example # Permissions can be anything, it will check that the player has the permission before opening
    Key:
      Item: TRIPWIRE_HOOK
      Name: '%type% Crate Key'
      Enchanted: true
    Hologram Text:
     - 'This crate will have'
     - 'Its own hologram text!'

# Settings for the Crate opening GUI (Time is seconds)
Use GUI: true
GUI Time: 10
Cooldown: 5

# If true it will stop players without the admin perm breaking crates
Crate Protection: false

# Disable players being allowed to drop keys to other players
Disable Key Dropping: false

# %crate% can be used to show the crate name
# If a crate has no specific hologram text set, this will be shown
Default Hologram Text:
- "%crate%"
- "Right-Click to Open!"
- "Left-Click to Preview!"