# [][][][][][][][][][][][][][][][][][][][][]
#             Crates Plus V1.0
# [][][][][][][][][][][][][][][][][][][][][]

Update Checks: true

Crate Items:
  Common:
    - IRON_SWORD:1:DAMAGE_ALL-3
    - COOKED_BEEF:32:DAMAGE_ALL-100
  Rare:
    - DIAMOND_SWORD:1:DAMAGE_ALL
    - COMMAND:gamemode c %name%
  Ultra:
    - DIAMOND_SWORD:1:DAMAGE_ALL-3
Crate Chances:
  Common: 85
  Rare: 14
  Ultra: 1
Crate Knockback:
  Common: 0.5
  Rare: 1.0
  Ultra: 2.0
Broadcast On Crate Open:
  Common: false
  Rare: false
  Ultra: true
Firework On Crate Open:
  Common: false
  Rare: false
  Ultra: true