# [][][][][][][][][][][][][][][][][][][][][]
#             Crates Plus V1.0
# [][][][][][][][][][][][][][][][][][][][][]

# ITEMNAME:AMOUNT:ENCHANTMENTS|SEPARATED|BY|PIPE|WITH|LEVELS|LIKE|THIS-3
# Commands can be like COMMAND:/give %name% 100 coins
Crate Items:
  Common:
    - IRON_SWORD:1:DAMAGE_ALL-3
    - COOKED_BEEF:32:DAMAGE_ALL-100
  Rare:
    - DIAMOND_SWORD:1:DAMAGE_ALL
  Ultra:
    - DIAMOND_SWORD:1:DAMAGE_ALL-3
Crate Chances:
  Common: 60
  Rare: 30
  Ultra: 10
Broadcast On Crate Open:
  Common: false
  Rare: false
  Ultra: true
Firework On Crate Open:
  Common: false
  Rare: false
  Ultra: true